version: '3.7'

networks:
  default:
    external: true
    name: lb-common

services:
  rhsso:
    image: ${REGISTRY_HOST}/hofund/hofund-rhsso:${TAG}
    deploy:
      replicas: "${rep_rhsso}"
      labels:
        traefik.frontend.rule: "Host:rhsso.local.io,rhsso.local.com"
        traefik.frontend.cors.accesscontrolallowmethods: "GET,POST"
        traefik.frontend.cors.accesscontrolalloworiginlist: "*"
        traefik.enable: "true"
        traefik.backend: "rhsso_back"
        traefik.port: "8080"
        traefik.backend.healthcheck.path: /auth/
        traefik.backend.healthcheck.interval: 1s
        traefik.backend.healthcheck.port: 8080
        traefik.backend.healthcheck.scheme: http
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RHSSO_USER: ${RHSSO_USER}
      RHSSO_PASSWORD: ${RHSSO_PASSWORD}
      # KEYCLOAK_LOGLEVEL: TRACE
      # RHSSO_IMPORT: ../realms/test.json
    volumes:
      - ./profile.properties:/srv/rhsso/standalone/configuration/profile.properties:rw
      - ../upload_scripts:/srv/rhsso/standalone/deployments:rw
    networks:
      - default
      # default :
      #     aliases : 
      #       - rhsso.local.io
